# Stage 1: Build
FROM python:{{python_version}}-slim AS builder
COPY --from=docker.io/astral/uv:latest /uv /uvx /bin/

ENV UV_PYTHON_PREFERENCE=only-system
ENV UV_PYTHON=/usr/local/bin/python

WORKDIR /app

COPY pyproject.toml ./
RUN uv sync --no-cache --no-dev


# Stage 2: Runtime
FROM python:{{python_version}}-slim
COPY --from=builder /app/.venv /app/.venv

ENV PATH="/app/.venv/bin:$PATH"

WORKDIR /app

COPY src .
CMD ["uvicorn", "--help"]
